apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-server
  labels:
    app: database_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database_server
  template:
    metadata:
      labels:
        app: database_server
    spec:
      containers:
      - name: database-server
        image: database_server
        imagePullPolicy: Never
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: database-server
  labels:
    app: database_server
spec:
  selector:
    app: database_server
  ports:
  - name: default
    port: 80
    targetPort: 9000

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: services-list
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: services-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: services-list
  apiGroup: rbac.authorization.k8s.io